name: Docker Compose Build Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose
        run: |
          docker compose config

      - name: Build Compose Stack
        run: |
          docker compose build